### ISSUE TITLE
.R icons not showing up.

### ISSUE THREAD

**Issue by jackolney** [vikjam/afterglow-theme#1] opened 2015-12-27 11:54 UTC
I can't seem to get .R icons to appear in the afterglow theme (see screenshot). I am running the latest version of ST and Afterglow (v2.1.2).
![screen shot 2015-12-27 at 11 48 02](https://cloud.githubusercontent.com/assets/4134882/12010109/079ff1ac-ac90-11e5-9e94-d1f8c55626d2.jpg)

I did wonder whether it is my preferences, as I was never sure how ST knew to look in the folder `./Packages/Theme - Afterglow/` but if I add that to the beginning of the theme path, then the whole interface screws up. No other version of the theme appears in my Application Support folder.

``` .json
{
    "color_scheme": "Packages/Theme - Afterglow/Afterglow-monokai.tmTheme",
    "theme": "Afterglow-orange.sublime-theme"
}
```

Any ideas on a fix for this would be greatly appreciated.

**Comment by vikjam** [comment] 2016-01-06 20:38
Hmm, this is disconcerting. I'm going to dig some more into this. Could you provide some more details on your set-up? It looks like you're running OS X--is it El Capitan? I'm assuming you're using Package Control, though you installed this fork of Afterglow manually.

**Comment by jackolney** [comment] 2016-01-06 21:49
Yep, I'm on the latest version of El Cap on one of my machines and the latest public beta on another – .R icons do not show up on either. I do use package control, but you are correct, I did install this fork of Afterglow manually.

Here is the entire contents of my user preferences file if that is of any help. I just can't figure it out!

``` json
{
    "always_show_minimap_viewport": true,
    "bold_folder_labels": true,
    "color_inactive_tabs": true,
    "color_scheme": "Packages/Theme - Afterglow/Afterglow-monokai.tmTheme",
    "detect_slow_plugins": true,
    "font_size": 9,
    "ignored_packages":
    [
        "Markdown",
        "Vintage"
    ],
    "indent_guide_options":
    [
        "draw_normal",
        "draw_active"
    ],
    "open_files_in_new_window": true,
    "overlay_scroll_bars": "enabled",
    "sidebar_no_icon": false,
    "spacefunk_sidebar_light": false,
    "status_bar_brighter": false,
    "tab_size": 4,
    "tabs_padding_medium": true,
    "tabs_small": true,
    "theme": "Afterglow-orange.sublime-theme",
    "translate_tabs_to_spaces": true
}

```

**Comment by vikjam** [comment] 2016-01-07 03:26
Sorry this is so annoying! I've done a couple of fresh installs (once on Windows 7 and once on OS X Yosemite), and I couldn't reproduce it. My hypothesis is it might have something to do with having previous installed Afterglow on your machine. If you'd liked to try to help me figure it out, would you mind trying the following:
- Close Sublime Text.
- Move the folder "/Users/$USER/Library/Application Support/Sublime Text 3/" to a safe place, so that you can restore it later. Note you should replace $USER with your username.
- Once you've removed the folder "Sublime Text 3" from "Application Support", restart Sublime.
- Then install this fork of the Afterglow Theme manually, and activate the theme like you've done before.

I think you should see the R icon:
![screen shot 2016-01-06 at 10 02 45 pm](https://cloud.githubusercontent.com/assets/1154799/12161456/f6ec34f6-b4c3-11e5-8535-6fb51b11f3a9.png)

If you quit Sublime Text, and replace the folder "Sublime Text 3" in "Application Support" with your original one that you saved in the second step, you should go back exactly to where you were.

I totally understand if you don't want to try this out! I'll keep messing with this (though ETA might be a little while), but I just thought it might be helpful to have two of us on the case!

**Comment by jackolney** [comment] 2016-01-07 09:22
Firstly, thanks very much for all the help – I figured that this was a pretty popular theme so maybe it was some config error on my part.

So, I closed ST, deleted the folder in Application Support. I then reopened ST (which populated the folder again), I then cloned Afterglow into the packages folder. I get an icon next to .R files, but now it is not the right one...

![screen shot 2016-01-07 at 09 17 14](https://cloud.githubusercontent.com/assets/4134882/12166763/192cc3d0-b520-11e5-8971-d12ba21a3364.png)

Bizarre, right?

**Comment by vikjam** [comment] 2016-01-09 22:33
Haha, my mind is blown! I think that's the icon Afterglow used to use before I changed it.

Just to be sure, did you rename the folder to `Theme - Afterglow` in `/Users/$USER/Library/Application Support/Sublime Text 3/Packages`?

**Comment by jackolney** [comment] 2016-01-10 22:06
Haha, well perhaps this is a sign of progress, if nothing else! Yep, i used `git clone https://github.com/Yabatadesign/afterglow-theme/ "Theme - Afterglow"` so I was definitely calling the correct folder. 

So presumably this indicates that some other junk is preventing any icons from being shown adjacent to .R files.

My only hunch is that the line `"theme": "Afterglow-orange.sublime-theme",` isn't describing the exact location of the theme folder. I'm guessing that this is some JSON trickery and ST knows that any folder starting with "Theme -" contains .sublime-theme files. Is that correct? But I'm also guessing that if the path was wrong, then ST would throw an error?

**Comment by vikjam** [comment] 2016-01-24 04:06
Here's another theory. I think it's a capitalization issue! I made some changes to the repository (perhaps a bit hastily). After you pull the changes (or download the updated zip), let me know how it goes!

**Comment by jackolney** [comment] 2016-01-24 10:05
Sucess!!

What was the fix? Just changing `file_type_r` to `file_type_R`?

Bizarre, that it was causing an issue on only my machine though? Thanks for fixing it!

![screen shot 2016-01-24 at 10 02 46](https://cloud.githubusercontent.com/assets/4134882/12535648/a732d1f6-c281-11e5-9451-1d70dc41afb6.jpg)

**Comment by vikjam** [comment] 2016-01-25 02:38
Nice!

I just made that small change and renamed the R icon files. I'm still need to figure out why this works, but do you mind if I close this issue out?

**Comment by jackolney** [comment] 2016-01-25 08:48
Great -- sure, I think we're all finished here anyway.

Thanks, again.

**Closed as completed** 2016-02-11 03:04 UTC
